<?php

declare(strict_types=1);

namespace App\Modules\MedicalRecord\Database\Seeders;

use App\Modules\MedicalRecord\Models\Medicamento;
use Illuminate\Database\Seeder;

final class MedicationSeeder extends Seeder
{
    public function run(): void
    {
        $medications = [
            // Analgésicos / Anti-inflamatórios
            [
                'nome' => 'Paracetamol 500mg',
                'principio_ativo' => 'Paracetamol',
                'apresentacao' => 'Comprimido 500mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Paracetamol 750mg',
                'principio_ativo' => 'Paracetamol',
                'apresentacao' => 'Comprimido 750mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Ibuprofeno 400mg',
                'principio_ativo' => 'Ibuprofeno',
                'apresentacao' => 'Comprimido revestido 400mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Ibuprofeno 600mg',
                'principio_ativo' => 'Ibuprofeno',
                'apresentacao' => 'Comprimido revestido 600mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Dipirona Sódica 500mg',
                'principio_ativo' => 'Dipirona Sódica',
                'apresentacao' => 'Comprimido 500mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Dipirona Sódica Gotas 500mg/mL',
                'principio_ativo' => 'Dipirona Sódica',
                'apresentacao' => 'Solução oral gotas 500mg/mL — frasco 20mL',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Naproxeno 500mg',
                'principio_ativo' => 'Naproxeno',
                'apresentacao' => 'Comprimido 500mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Nimesulida 100mg',
                'principio_ativo' => 'Nimesulida',
                'apresentacao' => 'Comprimido 100mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Cetoprofeno 100mg',
                'principio_ativo' => 'Cetoprofeno',
                'apresentacao' => 'Cápsula 100mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Diclofenaco Sódico 50mg',
                'principio_ativo' => 'Diclofenaco Sódico',
                'apresentacao' => 'Comprimido revestido 50mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Meloxicam 15mg',
                'principio_ativo' => 'Meloxicam',
                'apresentacao' => 'Comprimido 15mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Piroxicam 20mg',
                'principio_ativo' => 'Piroxicam',
                'apresentacao' => 'Cápsula 20mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Celecoxibe 200mg',
                'principio_ativo' => 'Celecoxibe',
                'apresentacao' => 'Cápsula 200mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Etoricoxibe 90mg',
                'principio_ativo' => 'Etoricoxibe',
                'apresentacao' => 'Comprimido revestido 90mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Ácido Acetilsalicílico 100mg',
                'principio_ativo' => 'Ácido Acetilsalicílico',
                'apresentacao' => 'Comprimido 100mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],

            // Antibióticos
            [
                'nome' => 'Amoxicilina 500mg',
                'principio_ativo' => 'Amoxicilina',
                'apresentacao' => 'Cápsula 500mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Amoxicilina + Clavulanato 875mg/125mg',
                'principio_ativo' => 'Amoxicilina + Clavulanato de Potássio',
                'apresentacao' => 'Comprimido revestido 875mg + 125mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Azitromicina 500mg',
                'principio_ativo' => 'Azitromicina',
                'apresentacao' => 'Comprimido 500mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Cefalexina 500mg',
                'principio_ativo' => 'Cefalexina',
                'apresentacao' => 'Cápsula 500mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Ciprofloxacino 500mg',
                'principio_ativo' => 'Ciprofloxacino',
                'apresentacao' => 'Comprimido revestido 500mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Levofloxacino 500mg',
                'principio_ativo' => 'Levofloxacino',
                'apresentacao' => 'Comprimido revestido 500mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Metronidazol 400mg',
                'principio_ativo' => 'Metronidazol',
                'apresentacao' => 'Comprimido 400mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Sulfametoxazol + Trimetoprima 400mg/80mg',
                'principio_ativo' => 'Sulfametoxazol + Trimetoprima',
                'apresentacao' => 'Comprimido 400mg + 80mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Clindamicina 300mg',
                'principio_ativo' => 'Clindamicina',
                'apresentacao' => 'Cápsula 300mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Doxiciclina 100mg',
                'principio_ativo' => 'Doxiciclina',
                'apresentacao' => 'Cápsula 100mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Norfloxacino 400mg',
                'principio_ativo' => 'Norfloxacino',
                'apresentacao' => 'Comprimido revestido 400mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Ampicilina 500mg',
                'principio_ativo' => 'Ampicilina',
                'apresentacao' => 'Cápsula 500mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Ceftriaxona 1g',
                'principio_ativo' => 'Ceftriaxona',
                'apresentacao' => 'Pó para solução injetável 1g',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Eritromicina 500mg',
                'principio_ativo' => 'Eritromicina',
                'apresentacao' => 'Comprimido revestido 500mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Claritromicina 500mg',
                'principio_ativo' => 'Claritromicina',
                'apresentacao' => 'Comprimido revestido 500mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],

            // Anti-hipertensivos
            [
                'nome' => 'Losartana Potássica 50mg',
                'principio_ativo' => 'Losartana Potássica',
                'apresentacao' => 'Comprimido revestido 50mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Enalapril 10mg',
                'principio_ativo' => 'Maleato de Enalapril',
                'apresentacao' => 'Comprimido 10mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Anlodipino 5mg',
                'principio_ativo' => 'Anlodipino',
                'apresentacao' => 'Comprimido 5mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Hidroclorotiazida 25mg',
                'principio_ativo' => 'Hidroclorotiazida',
                'apresentacao' => 'Comprimido 25mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Atenolol 50mg',
                'principio_ativo' => 'Atenolol',
                'apresentacao' => 'Comprimido 50mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Propranolol 40mg',
                'principio_ativo' => 'Cloridrato de Propranolol',
                'apresentacao' => 'Comprimido 40mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Valsartana 160mg',
                'principio_ativo' => 'Valsartana',
                'apresentacao' => 'Comprimido revestido 160mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Ramipril 5mg',
                'principio_ativo' => 'Ramipril',
                'apresentacao' => 'Cápsula 5mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Nifedipino 30mg',
                'principio_ativo' => 'Nifedipino',
                'apresentacao' => 'Comprimido de liberação prolongada 30mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Espironolactona 25mg',
                'principio_ativo' => 'Espironolactona',
                'apresentacao' => 'Comprimido 25mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Furosemida 40mg',
                'principio_ativo' => 'Furosemida',
                'apresentacao' => 'Comprimido 40mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Carvedilol 12,5mg',
                'principio_ativo' => 'Carvedilol',
                'apresentacao' => 'Comprimido 12,5mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],

            // Hipoglicemiantes
            [
                'nome' => 'Metformina 850mg',
                'principio_ativo' => 'Cloridrato de Metformina',
                'apresentacao' => 'Comprimido revestido 850mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Glibenclamida 5mg',
                'principio_ativo' => 'Glibenclamida',
                'apresentacao' => 'Comprimido 5mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Gliclazida 30mg MR',
                'principio_ativo' => 'Gliclazida',
                'apresentacao' => 'Comprimido de liberação modificada 30mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Sitagliptina 100mg',
                'principio_ativo' => 'Fosfato de Sitagliptina',
                'apresentacao' => 'Comprimido revestido 100mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Empagliflozina 10mg',
                'principio_ativo' => 'Empagliflozina',
                'apresentacao' => 'Comprimido revestido 10mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Dapagliflozina 10mg',
                'principio_ativo' => 'Dapagliflozina',
                'apresentacao' => 'Comprimido revestido 10mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Insulina NPH 100UI/mL',
                'principio_ativo' => 'Insulina Isofana (NPH)',
                'apresentacao' => 'Suspensão injetável 100UI/mL — frasco 10mL',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Insulina Regular 100UI/mL',
                'principio_ativo' => 'Insulina Regular',
                'apresentacao' => 'Solução injetável 100UI/mL — frasco 10mL',
                'lista_anvisa' => null,
                'controlado' => false,
            ],

            // Antidepressivos / Ansiolíticos
            [
                'nome' => 'Fluoxetina 20mg',
                'principio_ativo' => 'Cloridrato de Fluoxetina',
                'apresentacao' => 'Cápsula 20mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Sertralina 50mg',
                'principio_ativo' => 'Cloridrato de Sertralina',
                'apresentacao' => 'Comprimido revestido 50mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Escitalopram 10mg',
                'principio_ativo' => 'Oxalato de Escitalopram',
                'apresentacao' => 'Comprimido revestido 10mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Venlafaxina 75mg',
                'principio_ativo' => 'Cloridrato de Venlafaxina',
                'apresentacao' => 'Cápsula de liberação prolongada 75mg',
                'lista_anvisa' => 'C1',
                'controlado' => true,
            ],
            [
                'nome' => 'Amitriptilina 25mg',
                'principio_ativo' => 'Cloridrato de Amitriptilina',
                'apresentacao' => 'Comprimido revestido 25mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Bupropiona 150mg',
                'principio_ativo' => 'Cloridrato de Bupropiona',
                'apresentacao' => 'Comprimido de liberação prolongada 150mg',
                'lista_anvisa' => 'C1',
                'controlado' => true,
            ],
            [
                'nome' => 'Duloxetina 60mg',
                'principio_ativo' => 'Cloridrato de Duloxetina',
                'apresentacao' => 'Cápsula gastrorresistente 60mg',
                'lista_anvisa' => 'C1',
                'controlado' => true,
            ],
            [
                'nome' => 'Paroxetina 20mg',
                'principio_ativo' => 'Cloridrato de Paroxetina',
                'apresentacao' => 'Comprimido revestido 20mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Trazodona 100mg',
                'principio_ativo' => 'Cloridrato de Trazodona',
                'apresentacao' => 'Comprimido 100mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Mirtazapina 30mg',
                'principio_ativo' => 'Mirtazapina',
                'apresentacao' => 'Comprimido orodispersível 30mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],

            // Psicotrópicos B1
            [
                'nome' => 'Clonazepam 2mg',
                'principio_ativo' => 'Clonazepam',
                'apresentacao' => 'Comprimido 2mg',
                'lista_anvisa' => 'B1',
                'controlado' => true,
            ],
            [
                'nome' => 'Diazepam 10mg',
                'principio_ativo' => 'Diazepam',
                'apresentacao' => 'Comprimido 10mg',
                'lista_anvisa' => 'B1',
                'controlado' => true,
            ],
            [
                'nome' => 'Alprazolam 0,5mg',
                'principio_ativo' => 'Alprazolam',
                'apresentacao' => 'Comprimido 0,5mg',
                'lista_anvisa' => 'B1',
                'controlado' => true,
            ],
            [
                'nome' => 'Bromazepam 6mg',
                'principio_ativo' => 'Bromazepam',
                'apresentacao' => 'Comprimido 6mg',
                'lista_anvisa' => 'B1',
                'controlado' => true,
            ],
            [
                'nome' => 'Lorazepam 2mg',
                'principio_ativo' => 'Lorazepam',
                'apresentacao' => 'Comprimido 2mg',
                'lista_anvisa' => 'B1',
                'controlado' => true,
            ],
            [
                'nome' => 'Midazolam 15mg',
                'principio_ativo' => 'Midazolam',
                'apresentacao' => 'Comprimido 15mg',
                'lista_anvisa' => 'B1',
                'controlado' => true,
            ],
            [
                'nome' => 'Nitrazepam 5mg',
                'principio_ativo' => 'Nitrazepam',
                'apresentacao' => 'Comprimido 5mg',
                'lista_anvisa' => 'B1',
                'controlado' => true,
            ],
            [
                'nome' => 'Zolpidem 10mg',
                'principio_ativo' => 'Tartarato de Zolpidem',
                'apresentacao' => 'Comprimido revestido 10mg',
                'lista_anvisa' => 'B1',
                'controlado' => true,
            ],

            // Psicotrópicos B2
            [
                'nome' => 'Metilfenidato 10mg',
                'principio_ativo' => 'Cloridrato de Metilfenidato',
                'apresentacao' => 'Comprimido 10mg',
                'lista_anvisa' => 'B2',
                'controlado' => true,
            ],
            [
                'nome' => 'Lisdexanfetamina 50mg',
                'principio_ativo' => 'Dimesilato de Lisdexanfetamina',
                'apresentacao' => 'Cápsula 50mg',
                'lista_anvisa' => 'B2',
                'controlado' => true,
            ],
            [
                'nome' => 'Anfepramona 25mg',
                'principio_ativo' => 'Cloridrato de Anfepramona',
                'apresentacao' => 'Cápsula 25mg',
                'lista_anvisa' => 'B2',
                'controlado' => true,
            ],

            // Entorpecentes A1
            [
                'nome' => 'Morfina 10mg',
                'principio_ativo' => 'Sulfato de Morfina',
                'apresentacao' => 'Comprimido de liberação prolongada 10mg',
                'lista_anvisa' => 'A1',
                'controlado' => true,
            ],
            [
                'nome' => 'Codeína 30mg',
                'principio_ativo' => 'Fosfato de Codeína',
                'apresentacao' => 'Comprimido 30mg',
                'lista_anvisa' => 'A1',
                'controlado' => true,
            ],
            [
                'nome' => 'Fentanil 25mcg/h',
                'principio_ativo' => 'Citrato de Fentanil',
                'apresentacao' => 'Adesivo transdérmico 25mcg/h',
                'lista_anvisa' => 'A1',
                'controlado' => true,
            ],
            [
                'nome' => 'Oxicodona 10mg',
                'principio_ativo' => 'Cloridrato de Oxicodona',
                'apresentacao' => 'Comprimido de liberação prolongada 10mg',
                'lista_anvisa' => 'A1',
                'controlado' => true,
            ],
            [
                'nome' => 'Metadona 10mg',
                'principio_ativo' => 'Cloridrato de Metadona',
                'apresentacao' => 'Comprimido 10mg',
                'lista_anvisa' => 'A1',
                'controlado' => true,
            ],

            // Entorpecentes A2
            [
                'nome' => 'Tramadol 100mg',
                'principio_ativo' => 'Cloridrato de Tramadol',
                'apresentacao' => 'Comprimido de liberação prolongada 100mg',
                'lista_anvisa' => 'A2',
                'controlado' => true,
            ],
            [
                'nome' => 'Tapentadol 50mg',
                'principio_ativo' => 'Cloridrato de Tapentadol',
                'apresentacao' => 'Comprimido revestido 50mg',
                'lista_anvisa' => 'A2',
                'controlado' => true,
            ],

            // Outros controlados C1
            [
                'nome' => 'Tramadol 50mg',
                'principio_ativo' => 'Cloridrato de Tramadol',
                'apresentacao' => 'Comprimido 50mg',
                'lista_anvisa' => 'C1',
                'controlado' => true,
            ],
            [
                'nome' => 'Sibutramina 15mg',
                'principio_ativo' => 'Cloridrato de Sibutramina',
                'apresentacao' => 'Cápsula 15mg',
                'lista_anvisa' => 'C1',
                'controlado' => true,
            ],
            [
                'nome' => 'Topiramato 50mg',
                'principio_ativo' => 'Topiramato',
                'apresentacao' => 'Comprimido 50mg',
                'lista_anvisa' => 'C1',
                'controlado' => true,
            ],

            // Antirretrovirais C4
            [
                'nome' => 'Tenofovir 300mg',
                'principio_ativo' => 'Tenofovir Disoproxil Fumarato',
                'apresentacao' => 'Comprimido 300mg',
                'lista_anvisa' => 'C4',
                'controlado' => true,
            ],
            [
                'nome' => 'Lamivudina 150mg',
                'principio_ativo' => 'Lamivudina',
                'apresentacao' => 'Comprimido 150mg',
                'lista_anvisa' => 'C4',
                'controlado' => true,
            ],
            [
                'nome' => 'Dolutegravir 50mg',
                'principio_ativo' => 'Dolutegravir Sódico',
                'apresentacao' => 'Comprimido 50mg',
                'lista_anvisa' => 'C4',
                'controlado' => true,
            ],

            // Retinoides C2
            [
                'nome' => 'Isotretinoína 20mg',
                'principio_ativo' => 'Isotretinoína',
                'apresentacao' => 'Cápsula 20mg',
                'lista_anvisa' => 'C2',
                'controlado' => true,
            ],
            [
                'nome' => 'Acitretina 25mg',
                'principio_ativo' => 'Acitretina',
                'apresentacao' => 'Cápsula 25mg',
                'lista_anvisa' => 'C2',
                'controlado' => true,
            ],

            // Imunossupressores C3
            [
                'nome' => 'Talidomida 100mg',
                'principio_ativo' => 'Talidomida',
                'apresentacao' => 'Comprimido 100mg',
                'lista_anvisa' => 'C3',
                'controlado' => true,
            ],

            // Anabolizantes C5
            [
                'nome' => 'Cipionato de Testosterona 200mg/mL',
                'principio_ativo' => 'Cipionato de Testosterona',
                'apresentacao' => 'Solução injetável 200mg/mL — ampola 1mL',
                'lista_anvisa' => 'C5',
                'controlado' => true,
            ],
            [
                'nome' => 'Decanoato de Nandrolona 50mg/mL',
                'principio_ativo' => 'Decanoato de Nandrolona',
                'apresentacao' => 'Solução injetável 50mg/mL — ampola 1mL',
                'lista_anvisa' => 'C5',
                'controlado' => true,
            ],
            [
                'nome' => 'Oxandrolona 2,5mg',
                'principio_ativo' => 'Oxandrolona',
                'apresentacao' => 'Comprimido 2,5mg',
                'lista_anvisa' => 'C5',
                'controlado' => true,
            ],

            // Outros comuns
            [
                'nome' => 'Omeprazol 20mg',
                'principio_ativo' => 'Omeprazol',
                'apresentacao' => 'Cápsula gastrorresistente 20mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Pantoprazol 40mg',
                'principio_ativo' => 'Pantoprazol Sódico',
                'apresentacao' => 'Comprimido gastrorresistente 40mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Ranitidina 150mg',
                'principio_ativo' => 'Cloridrato de Ranitidina',
                'apresentacao' => 'Comprimido revestido 150mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Domperidona 10mg',
                'principio_ativo' => 'Domperidona',
                'apresentacao' => 'Comprimido 10mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Ondansetrona 8mg',
                'principio_ativo' => 'Cloridrato de Ondansetrona',
                'apresentacao' => 'Comprimido revestido 8mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Loratadina 10mg',
                'principio_ativo' => 'Loratadina',
                'apresentacao' => 'Comprimido 10mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Desloratadina 5mg',
                'principio_ativo' => 'Desloratadina',
                'apresentacao' => 'Comprimido 5mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Montelucaste 10mg',
                'principio_ativo' => 'Montelucaste Sódico',
                'apresentacao' => 'Comprimido revestido 10mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Prednisolona 20mg',
                'principio_ativo' => 'Prednisolona',
                'apresentacao' => 'Comprimido 20mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Prednisona 20mg',
                'principio_ativo' => 'Prednisona',
                'apresentacao' => 'Comprimido 20mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Dexametasona 0,5mg',
                'principio_ativo' => 'Dexametasona',
                'apresentacao' => 'Comprimido 0,5mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Levotiroxina Sódica 50mcg',
                'principio_ativo' => 'Levotiroxina Sódica',
                'apresentacao' => 'Comprimido 50mcg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Sinvastatina 20mg',
                'principio_ativo' => 'Sinvastatina',
                'apresentacao' => 'Comprimido revestido 20mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Atorvastatina 20mg',
                'principio_ativo' => 'Atorvastatina Cálcica',
                'apresentacao' => 'Comprimido revestido 20mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
            [
                'nome' => 'Rosuvastatina 10mg',
                'principio_ativo' => 'Rosuvastatina Cálcica',
                'apresentacao' => 'Comprimido revestido 10mg',
                'lista_anvisa' => null,
                'controlado' => false,
            ],
        ];

        Medicamento::query()->upsert(
            $medications,
            uniqueBy: ['nome', 'principio_ativo'],
            update: ['apresentacao', 'lista_anvisa', 'controlado'],
        );
    }
}
